### ISSUE TITLE
Migration (AidStream to Publisher)

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1328] opened 2023-11-29 05:49 UTC
Migrate the activity data of publisher "GB-GOV-9" from AidStream to Publisher.

Note that: 
- The publisher has already created an IATI Publisher account, which is set up correctly linked to the Registry. They have also started populating organisation data and default values in IATI Publisher. Therefore - **can we migrate just activity data across from AidStream?**
- There are 3 activities in AidStream, which have recently had data corrected (e.g. reporting-org/@ref and activity IDs). However, the changes have not been republished to the Registry (due to an incorrect API token) - **can we migrate the activity data as it is in AidStream, and not the published version on the Registry?**

The conversation with the publisher can be found in this Zendesk support ticket: https://iati.zendesk.com/agent/tickets/42657

**Comment by IsabelBirds** [comment] 2023-11-30 15:59
Hi Prawesh 

Just to confirm that the iati-identifier of all published activities must **not** change in this transfer, as per the standard (https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/iati-identifier/).

So, we will be using the correct org-id (GB-GOV-GB-9) going forward
* In the iati-identifier of all **new** activities
* In the org file 
* In all references to DWP as the reporting org/participating org etc

**But** any **existing activities** should continue to have their current prefix in their iati-identifier, even if this is incorrect.

**Comment by stevieflow** [comment] 2023-12-01 08:49
Agreed.  The ``activity-identifier`` cannot change once published

If an ``reporting-org``changes, then the ``other-identifier`` element can be used to express that: https://iatistandard.org/en/iati-standard/203/activity-standard/iati-activities/iati-activity/other-identifier/, with the code B1: https://iatistandard.org/en/iati-standard/203/codelists/otheridentifiertype/

This codelist also states about ``activity-identifier`` not changing - although it kind of offers an unhelpful escape route through the name of code A3 I think :(

**Comment by praweshsth** [comment] 2023-12-04 08:18
@IsabelBirds @stevieflow @robredpath @odscrachel 

Currently, in Publisher, if we change the organisation identifier in the organisation data, the iati activity identifiers for both published and not-published activities also changes, as the iati activity identifier is not stored in the database rather it is generated by concatenation of organisation identifier and activity identifier (provided by user at the time creating a new activity). However, the change is not reflected in published XML file until the published activities are republished. For this matter, we have to make changes in the publisher to address such situation in future. 

For now, we can migrate the organisation with old org-id. But we have to make above mentioned changes in publisher to make sure when the organisation changes the org-id to new one, it works for them. 

We will work on the estimate to make the changes, which we can discuss later. Please suggest us if there are any alternative solutions for the issue mentioned above?

**Comment by robredpath** [comment] 2024-01-04 12:37
Quick update for any interested observers: @praweshsth has provided his team's estimate for the work to maintain activity IDs when org IDs change, and I've ask them to proceed. I hope this will be resolved fairly quickly, now.

**Comment by praweshsth** [comment] 2024-01-05 05:31
@robredpath We will first work on this from next week.

**Comment by robredpath** [comment] 2024-01-11 10:14
@praweshsth has this issue been closed in error?

 I see that the issue is closed but AFAIK the migration hasn't happened yet, nor has the change to make sure that activity IDs don't change been completed.

**Comment by praweshsth** [comment] 2024-01-11 10:28
> @praweshsth has this issue been closed in error?
> 
> I see that the issue is closed but AFAIK the migration hasn't happened yet, nor has the change to make sure that activity IDs don't change been completed.

Thank you for informing. I was cleaning up the issue board and I mistakenly closed it. Thank you once again for informing me.

**Comment by emmajclegg** [comment] 2024-02-13 17:30
Pausing this issue for now, given the dependency on [#1364](https://github.com/younginnovations/iatipublisher/issues/1364) and/or changes being made to this publisher's data in AidStream/the Registry

**Comment by emmajclegg** [comment] 2024-03-28 22:43
@praweshsth - this is the migration request that's been stalled for a while but we're now ready to do.

I've edited the description at the top of this issue with a summary of the request. The publisher has already registered on IATI Publisher in this instance and we would like to transfer activity data across from AidStream in the easiest way possible.

Any questions let me know - happy to discuss on Tuesday!

**Comment by praweshsth** [comment] 2024-04-02 11:58
@emmajclegg - need to republish the changes in the AidStream then we can migrate it to Publisher.

**Comment by emmajclegg** [comment] 2024-04-03 15:27
@praweshsth - I can confirm that I've republished this publisher's activity file (3 activities) from AidStream so the activity data is now ready for migration. There are no data quality issues flagged by the IATI Validator.

**Comment by Sanilblank** [comment] 2024-04-09 04:51
@emmajclegg - The organisation has been successfully migrated in the production server. Please have a look.

cc. @PG-Momik @praweshsth @sarinasindurakar

**Comment by emmajclegg** [comment] 2024-04-09 18:28
Thank you @Sanilblank - I've let the publisher know and will close this issue at the end of the week if no problems have been highlighted.

**Closed** 2024-04-12 15:33 UTC
Labels: priority: medium, ODS
