### ISSUE TITLE
Fix issue in the downloaded CSV file of activity

### ISSUE THREAD

**Issue by praweshsth** [younginnovations/iatipublisher#1340] opened 2024-01-12 05:04 UTC
Here's the scenario for downloaded CSV and the issue:

**Scenario:**
I've logged in to IATI Publisher and proxied an account. Firstly, I used the Download All function from the activities list. Then I selected the first two activities and downloaded them. I'm attaching the two files I received, each replicating the errors the requestor described.`

### Steps to replicate 
1. Add  activity
2. Fill all the element of activity
3. Select around 3-4 activities to download in activity listing page.
4. Click on download icon
5. Click on download csv

### Issues
- [ ] 1.  The activity title, contact elements details are not shown in the csv file all the activities.
- [ ] 2. The planned start date is also not shown in second activity in the csv file.
- [ ] 3.  If the user downloads a CSV file containing 2-3 activities, the details of elements in the third activity are not displayed in the CSV file. For instance check attached file:
[pub_937930_2024_01_12_054535.csv](https://github.com/younginnovations/iatipublisher/files/13916012/pub_937930_2024_01_12_054535.csv)
- [x] 4. The CSV file should be downloaded with activities arranged in the same order as they appear in the user interface.
**In csv File :**
![Image](https://github.com/younginnovations/iatipublisher/assets/65848732/e4212558-79a0-4e5e-8436-2ce481c8ca1f)
**In UI**
![Image](https://github.com/younginnovations/iatipublisher/assets/65848732/dc5abfb3-c550-441a-8a48-260e2d87bbf1)

**Comment by sarinasindurakar** [comment] 2024-01-17 08:56
Issue number 1 is not an issue since activity narratives with the default language are included in the CSV file. However, if the activity elements' narratives are in a different language, they won't be displayed in the CSV file.

**Comment by siwhitehouse** [comment] 2024-01-22 22:33
@praweshsth I don't think this is a full or clear description of the issue I raised. Also, you have added new problems that I assume you have found and that you think are connected.

@sarinasindurakar and @A4family - as the two participants to this issue - can you tell me what you think the issue is and what progress you have made, please?

I am happy to tell you what problem has been raised with me. Also, if we can resolve #1352 then I will try and recreate this in Staging and without the need to reference individuals or their organisations in this open GH repository.

**Comment by praweshsth** [comment] 2024-01-24 10:10
@siwhitehouse This is what we have understood:

When user downloads the CSV file of activities, the activity plan start date and end date are not showing up. However, when we checked and found some other data are also not showing up. Hence we decided to work on those when we are fixing the issue raised by you. Please inform us if we have missed anything regarding this.

**Comment by siwhitehouse** [comment] 2024-01-24 22:27
Thank you @praweshsth - that is clearer and is a good understanding of the query.

**Comment by praweshsth** [comment] 2024-01-25 04:12
@siwhitehouse we have completed this. Please check in staging and provide feedback on this or confirm it is good to be closed.

**Comment by siwhitehouse** [comment] 2024-01-25 13:23
@praweshsth Could you copy this organisation's account into Staging, please?

**Comment by praweshsth** [comment] 2024-01-26 05:33
We will create an account in the staging.

**Comment by praweshsth** [comment] 2024-01-26 09:13
@siwhitehouse the organisation has been added in the staging.

**Comment by siwhitehouse** [comment] 2024-02-02 19:49
This appears to be fixed in Live. Thank you @praweshsth

**Closed by siwhitehouse** 2024-02-02 19:49 UTC
Labels: Bug, ODSC
