### ISSUE TITLE
#152 Bug: UI issues

### ISSUE THREAD

**Issue by AbhishekSka** [younginnovations/iatipublisher#159] opened 2022-05-27 10:23 UTC
### Context

- Desktop
- Chrome 100.0.4896.127

### Precondition
- https://stage.iatipublisher.yipl.com.np/registration

### Step
_Issue 1_

- [x]  Check for the font color of field labels in Step 1/Step2 

_Issue 2_

- [x] Font color for "Step 2 out of 3"

_Issue 3_

- [x]  Text color over "NEXT STEP"
![image](https://user-images.githubusercontent.com/25945530/170678085-a95d3196-f946-4000-ad8b-672466d661d9.png)

_Issue 4_

- [x] Turncated tool tip (Resolution: 1366x768 View port:1312x627)
![image](https://user-images.githubusercontent.com/25945530/170940187-7392feec-a78d-4b31-8d51-6dd4895d2ce8.png)

_Issue 5_
- [x] Upon going back to "Administrator Information" to "Publisher Information"
![image](https://user-images.githubusercontent.com/25945530/171092202-c6e97008-d18c-4639-9f0a-ef2a0a163994.png)

### Actual result
- Font color #000000

### Expected result
- As per figma 
 - Issue 1>>#2A2F30
 - Issue 2>>#2A2F30
 - Issue 3>> #155366

![image](https://user-images.githubusercontent.com/25945530/170681763-20f0b02f-a9c4-4185-ac7c-392839811e04.png)

**Comment by Man0zZ** [comment] 2022-06-03 06:09
@AbhishekSka this issue has been resolved. Test it out and if there is any issue please give me feedback.

cc @man-git007
cc @praweshsth

**Comment by SauravSilwal10** [comment] 2022-06-03 11:40
@Man0zZ  issue 3 hasn't been solved yet.According to the figma design Text color over "NEXT STEP" should be #155366 but actual result is #2A2F30.

cc @man-git007 
cc @praweshsth

**Comment by Man0zZ** [comment] 2022-06-06 08:58
@AbhishekSka  @SauravSilwal10  I discussed issue 3 with designers  and  they says to use #2A2F30 color which is currently used. Since, sign in and next step buttons are similar they should be same color.

cc @man-git007
cc @praweshsth

**Comment by man-git007** [comment] 2022-09-14 02:59
@SauravSilwal10 @Man0zZ @AbhishekSka Can we close this issue?

**Comment by man-git007** [comment] 2022-09-14 06:06
@nirvanalama Can you look at issue no. 3 and this [link](https://github.com/younginnovations/iatipublisher/issues/159#issuecomment-1145877576)

**Comment by nirvanalama** [comment] 2022-09-14 06:29
The issue is not clear. @man-git007  The link is of the same issue.

**Comment by titungdup** [comment] 2022-09-14 09:36
@man-git007 Issue no. 3 is resolved. We can close this issue.

**Closed by titungdup** 2022-09-14 09:36 UTC
Labels: type: bug, Frontend
