### ISSUE TITLE
Issue while importing CSV/XML 

### ISSUE THREAD

**Issue by SauravSilwal10** [younginnovations/iatipublisher#837] opened 2022-12-01 09:25 UTC
Context
- Desktop
- Chrome

Precondition
- https://iatipublisher-dev.yipl.com.np/
- Username: testing
- Password: 12345678

Steps
- Import CSV/XML file 

Actual Result

- An unwanted error message is displayed." SQLSTATE[08006] [7] connection to server at "private-yi-prod-postgres-do-user-4025190-0.b.db.ondigitalocean.com" (10.122.0.13), port 25060 failed: could not open certificate file "/root/.postgresql/postgresql.crt": Permission denied connection to server at "private-yi-prod-postgres-do-user-4025190-0.b.db.ondigitalocean.com" (10.122.0.13), port 25060 failed: FATAL: no pg_hba.conf entry for host "10.122.0.18", user "iatipublisher_dev", database "iatipublisher_dev", no encryption (SQL: select "iati_identifier" from "activities" where "org_id" = 28)"

Excepted Result

- Import activity should work properly.

https://user-images.githubusercontent.com/78422663/205015063-b70e3a4d-2d90-4f56-90f3-a925010b269c.mp4

**Comment by man-git007** [comment] 2022-12-01 10:05
@pravinbanjade Please look into this.

cc @praweshsth

**Comment by pravinbanjade** [comment] 2022-12-01 10:31
It seems to be a certificate validation issue when accessing to database from a non-SSL IP address.
The problem is fixed on `837-import-activity-fix` branch. Please merge the branch to develop and test further. If you still face the problem, reply to this thread.

**Comment by man-git007** [comment] 2022-12-01 11:04
@pravinbanjade Would this certificate be the same for all three (dev, stage, and production) environments?

**Comment by pravinbanjade** [comment] 2022-12-01 11:06
@man-git007 yes. It is same for all env

**Comment by SauravSilwal10** [comment] 2022-12-01 11:32
@pravinbanjade This issue persists while importing the XML file. Please review it again.

https://user-images.githubusercontent.com/78422663/205042265-9e5aad34-f193-4de8-821f-4080aee7429b.mp4

**Comment by man-git007** [comment] 2022-12-06 04:30
@pravinbanjade @sriza Can we close this issue?

cc @SauravSilwal10

**Comment by pravinbanjade** [comment] 2022-12-06 04:35
Yes, this issue is solved by @sriza. You may now close the issue.

cc: @man-git007 @SauravSilwal10

**Comment by man-git007** [comment] 2022-12-06 04:45
@sriza Lets close this issue if there is no other bugs left

**Comment by sriza** [comment] 2022-12-06 05:24
Issue closed manually

**Closed by sriza** 2022-12-06 05:24 UTC
Labels: type: bug, priority: critical, DevOps
