### ISSUE TITLE
Recipient Country % Calculation

### ISSUE THREAD

**Issue by DaveEade49** [younginnovations/iatipublisher#1187] opened 2023-04-25 13:59 UTC
One of our publishers that has multiple countries for an activity is getting a "not completed" warning.

https://publisher.iatistandard.org/activity/3139

When you manually add up the % they add up to 100%, however two of the countries have brackets ( ) in their name, and as the % values are also contained within brackets I was wondering whether that is where the logic is being tripped up.

Can you please check and advise?

Thanks
Dave

**Comment by sarinasindurakar** [comment] 2023-04-27 08:31
- [ ] When user adds the percentage in decimal, more than 100% is accepted in recipient region and in recipient country too.
![image](https://user-images.githubusercontent.com/65848732/234794907-05de7234-51c1-4c9a-8ad6-fae5c4bcae7c.png)

- [ ]  when all the data of the recipient country is removed, the recipient country is shown in listing side.

https://user-images.githubusercontent.com/65848732/234803105-0a5d3f22-a79c-419e-bab2-c8ebe578840d.mp4

- [ ] when user enters the recipient region 100% and enters the code in recipient  country then both are completed.

**Comment by DaveEade49** [comment] 2023-04-27 15:54
I'm sorry - I don't understand the response.

This activity has 23 Recipient Countries.

The individual entries add up to 100%.

There are no entries for Recipient Region.

I do not understand why the element is shown as "not complete"

**Comment by sriza** [comment] 2023-04-28 08:27
@DaveEade49 
We have resolved this issue and merged this into the main branch. The issue was caused by the inability of the PHP language itself to compare decimal digits.
Please let us know if a similar issue arises.

cc @praweshsth

**Comment by praweshsth** [comment] 2023-04-28 12:14
@DaveEade49 this has been resolved and I have sent you an email on this as well. Please check and close this issue.

**Closed** 2023-04-28 12:33 UTC
