### ISSUE TITLE
IATI Publisher not publishing transactions to activity file XML

### ISSUE THREAD

**Issue by emmajclegg** [younginnovations/iatipublisher#1363] opened 2024-02-06 19:52 UTC
Multiple IATI Publisher users have reported that all activity transactions are now missing from their published IATI activity file. The transactions appear saved and published in IATI Publisher, but are not visible in their activity file on the IATI Registry.

It looks like these users have published (or republished) their activity data using IATI Publisher recently, since the 31st January.

I have replicated this issue today on the IATI Publisher staging site with the following test account and activity:
- _organisation name:_ emma-troubleshooting
- _activity iati-identifier:_ CA-CC-XXX-999-TEST-1
- _activity title:_ Troubleshooting IATI Publisher

This activity has 2 transactions showing as [published within IATI Publisher](https://iatipublisher-staging.yipl.com.np/activity/563), which are also present in the activity XLS download from Publisher. However, no transactions are visible in the [XML file ](https://staging.iatiregistry.org/dataset/emmac-test-activities) on the IATI Registry staging site. 

(Screenshots from IATI Publisher:)
![image](https://github.com/younginnovations/iatipublisher/assets/137316374/094b407e-d32e-45a1-81ed-58c36c7b5f62)

![Capture d’écran, le 2024-02-06 à 14 50 59](https://github.com/younginnovations/iatipublisher/assets/137316374/0170e793-b58c-441e-8671-d2232a29727b)

**Comment by praweshsth** [comment] 2024-02-07 04:10
- [ ] Fix the bug
- [ ] change the XML file of the published activities and republish them with same published date rather than current date

**Comment by robredpath** [comment] 2024-02-07 11:14
Thanks @praweshsth ! Could you let us know a little more about how this part of the system works, and what happened? 

We were surprised by this because we expected the XML download in the Publisher UI to be the same as the XML that's listed in the Registry.

**Comment by emmajclegg** [comment] 2024-02-07 17:28
Thanks for the information @PG-Momik and @praweshsth - let me know when the fix has been deployed and I'll check the affected publishers' transaction data.

**Comment by PG-Momik** [comment] 2024-02-08 11:44
Hi @emmajclegg , 
The bug fix has been deployed to stage and is ready to be deployed to production. Activities will now be published with their transaction.

To fix broken data with, we can do any of the following:
1. Let users republish the affected activities.
2. Run a script to fix the activities.

The script is currently being tested by our QA. Once its approved, it can be executed on production.

> [!NOTE]
> Do note that the script will only affect `published` activities and will not affect activities `republish` state.

**Comment by emmajclegg** [comment] 2024-02-11 23:10
To clarify @PG-Momik - has the first part of this (the bug fix to ensure activities publish with transactions) been deployed to production? Are we now focusing on the second part (the script to retrospectively republish affected publishers' activities)? 

The retrospective republishing script will be needed as us in IATI Support won't be aware of all of the affected publishers, only those that have contacted us. But if this is holding up deploying the main bug fix, please do that first (from my testing on staging last week, it looked like transactions were publishing as expected)

**Comment by praweshsth** [comment] 2024-02-12 04:29
@emmajclegg the bug fixing has not yet been deployed in the production but we can deploy it. and then fix the activities of the organisations that were affected by the bug. We can do both of these today.

**Comment by praweshsth** [comment] 2024-02-12 11:51
The bug has been deployed but we are working on the script to fix the existing xml files of already published activities. @emmajclegg

**Comment by PG-Momik** [comment] 2024-02-14 09:19
@emmajclegg , the script has been deployed and executed to production. Here's what the script does:
- Fetch assumed broken activities by fetching all activities that were published after Dec 01, 2023.
- Filter assumed broken activities by comparing number of transactions in database vs number of transactions in xml.
- Iterate over the filtered activities and, if the number of transactions in database and xml are not the same we add the said activity to a list of confirmed broken activities.
- The script iterates over all confirmed broken activities, and regenerates + replaces the broken `<iati-activity>` node in the merged xml that the registry points to.
- To  confirm if the script successfully fixed an activity, we once again compare the number of transactions in database vs xml. We also check that the `last-updated-datetime` attribute of `<iati-activity>` node has not changed.

**Comment by PG-Momik** [comment] 2024-02-20 05:24
This has been completed and deployed to main. But it was reopened to reply to mention the inner-working of the script.
cc: @praweshsth @emmajclegg @robredpath

**Closed by PG-Momik** 2024-02-20 05:24 UTC
Labels: Bug, priority: critical, ODSC
